PaloAltoNetworks/pan-os-ansible

- plugins/modules/panos_admpwd.py
panos_admpwd hangs or crashes when using with python3
underlying paramiko library returns bytes instead of str when used in python3 vs python2. The panos_admpwd expects only str to be returned. This patch uses the Ansible recommended to_text function to switch handle bytes vs str return data as documented here: 
https://docs.ansible.com/ansible/latest/dev_guide/developing_python_3.html#unicode-sandwich-common-borders-places-to-convert-bytes-to-text-in-controller-code 
Launching instances in AWS when using python3 should work as expected. 
Fixes issue #12 
Launching with ansible-playbook -vvv eventually shows the following stack trace:
```json
"module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_panos_admpwd_payload_g3f1ms1g/ansible_panos_admpwd_payload.zip/ansible/mo …
```
> fix for #12 - panos_admpwd hangs with python3

- plugins/modules/panos_software.py
Uses the default of 1200 seconds based on existing PanDevice.__init__ defaults.  Required for situations where appliances/vms take more than 20 minutes to complete installation tasks.
> Add new `timeout` arg to panos_software

- plugins/modules/panos_nat_rule.py
The module indicates a list is acceptable for destination_zone, but in reality it get's converted to an a string that looks like a json list that is not correct.
Update destination_zone on NAT module
It was not working as expected. 
Just locally, and copied over changes. 
- [x ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes if appropriate.
- [ x] All new and existing tests passed.
> Dst zone as str

- plugins/modules/panos_export.py
New module supporting export operations.  This module can export:
- Configuration
- Certificates/Keys
- Response pages
- Packet captures
- Technical support data
- Stats dump files
- Device State
This wasn't previously supported.
Fixes #53.
Tested against PAN-OS 9.0 and 10.0.
> New module: panos_export

- plugins/modules/panos_ipsec_profile.py
Removed lifetime as an Ansible required parameter, was breaking removal of IPsec profiles unless one was specified.  Module already uses a default value (1 hour) if none is specified when adding a profile.
Tested against PAN-OS 10.0.
> Remove required lifetime param - fixes #40.

- plugins/modules/panos_bgp.py
Added a `global_bfd_profile` parameter to the `bgp_params` list.
Per issue #20 the parameter was missing.  It was already supported in pandevice.network.Bgp.
Syntax checking.  Need to test against device VR.
none
> Added BFD profile param

- plugins/modules/panos_type_cmd.py
Work around in case the requested XPATH returns a list rather than a single element.  Fixes #38.
Tested against PAN-OS 10.0.
> panos_type_cmd - Fix return value when XPATH returns list.

- plugins/modules/panos_ike_gateway.py
Support for dynamic IKE peer in `panos_ike_gateway`.
Partial for #10. Adding FQDN support will require pandevice changes. 
Tested against PAN-OS 8.1, 9.0.
> panos_ike_gateway - Support dynamic IKE peer

- plugins/modules/panos_facts.py
`panos_facts` did not support Panorama.  This allows the module to gather the appropriate subsets on Panorama (system, ha, and config).
Tested against PAN-OS 9.0 and 10.0.
> Update panos_facts to support Panorama.  Fixes #62.

- plugins/modules/panos_administrator.py
`panos_administrator` could only add administrators to a template, not Panorama itself.  This uses the new `template_is_optional` flag to allow the module to modify Panorama directly.
Tested on PAN-OS 10.0.
> fix(panos_administrator): Add template_is_optional flag

- plugins/modules/panos_custom_url_category.py
Add custom url category module
* We are using this CustomUrlCategory PaloAlto feature in our company. 
* There is a small bug in pandevice which I'm not able to fix since the repo is forwarding to the new project pan-os-python. The bug has been fixed there. Because of this bug I had to define a CustomUrlDefinition class in the module code itself. This can be removed when the project is migrated to pan-os-python.
* The module supports only creation of CustomUrlCategory. It could be extended to support remove.
* This pull request is related somehow to [75](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/75)
It was tested locally on our Panorama.
I created a simple playbook and run it against the Panorama instance. I have tested with 7000+ records.
- New feature (non-breaking …
> Add custom url category module

- plugins/modules/panos_ike_gateway.py
Clarify docs around local_id_type, local_id_value, peer_id_type,
peer_id_value, local_ip_address, local_ip_address_type
Fixes #83
> fix: Require 'local_ip_address', 'local_ip_address_type' together

- plugins/modules/panos_tag_object.py
> fix: Don't look up tag color when state is absent

- plugins/modules/panos_bgp_policy_rule.py
Fixes #116
`panos_bgp_policy_rule` had an option `address_prefix` that was treated as a list of either strings or dicts.  This actually breaks sanity checks:
- Options should only have one type
- If the type is list, elements should only have one type
This change removes the code handling the string elements case, and makes the option be a list of dicts.
See below.
See below (TBD):
- Breaking change (fix or feature that would cause existing functionality to change)
> fix: address_prefix should be list of type dict

- plugins/modules/panos_security_rule_facts.py
> fix: panos_security_rule facts should support 'shared'

- plugins/modules/panos_security_rule_facts.py
Ansible doesn't allow for deprecating return values, but this also
simplifies the return values to 'rule_names' and 'rule_details'.
Fixes #128
> feat(panos_security_rule_facts): Support 'match_rules'

- plugins/modules/panos_custom_url_category.py
- tests/integration/firewall/test_panos_custom_url_category.yml
pan-os-python doesn't properly support category matches in CustomUrlCategory yet, so don't use this parameter until it does.
Fixes #143
> fix(panos_custom_url_category): Don't use type parameter

- plugins/modules/panos_software.py
panos_software module always downloads software even if it has already been downloaded. This patch adds a simple check before initiating the downloading. For upgrade / downgrade playbooks this saves a considerable amount of time.
Currently upgrades and downgrades much ensure the initial major release is present on the box. The current behavioure forces a lengthy redownload every time the playbook is run. This patch only downloads software if it is not already downloaded on the device. 
Collection installed locally and software upgrade downgrades performed
- [*] I have updated the documentation accordingly.
- [*] I have read the **CONTRIBUTING** document.
> panos_software download optimization

- plugins/modules/panos_export.py
According to the docs, to export a certificate the pan-os API expects the "include-key" param to be passed, with an expected value of yes or no.
However, the panos_export module is instead passing a "include-keys" param to the pan-os API, which is not an expected param.
Fixes https://github.com/PaloAltoNetworks/pan-os-ansible/issues/163
Tested against Panorama running Pan-OS 9.1.4
Before fix:
After fix:
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes if appropriate.
- [x ] All new and existing tests passed.
> fix(panos_export): Rename include-keys param for certificate export

- plugins/module_utils/panos.py
related to #129 
https://github.com/PaloAltoNetworks/pan-os-ansible/blob/af9faa4f6f18b421f5a14656adb81e84c35eb333/plugins/module_utils/panos.py#L117 still suggests installing pandevice. once that's installed the deprecation warning shows up:
```
[DEPRECATION WARNING]: Python library "pandevice" is now "pan-os-python" and is now 1.0! Please "pip install pan-os-python" at your earliest convenience. This feature will be removed from paloaltonetworks.panos in version 3.0.0.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
`pandevice` is deprecated in favor of `pan-os-python`.
It is just an update to the message shown to the user.
-
- Documentation(?)
I don't think this needs documentation updates anywhere.
I'm unable to find this document. It's …
> Don't recommend deprecated pandevice dependency

- plugins/modules/panos_import.py
I have added a new category option to enable uploading SAML metadata configuration to pan-os. 
All changes are in the file  ./plugins/modules/panos_import.py
Changes:
- Added "idp-metadata" as an optional category.
- Added "profile_name" as an option which is required when importing SAML metadata files.
- Added an example for SAML import.
- 
idp-metadata is the category defined in the api and profile-name is a required parameter for that category.
Documentation used for finding the category and parameter: [paloaltonetworks configure saml 2.0 xml api](https://docs.paloaltonetworks.com/pan-os/8-1/pan-os-panorama-api/pan-os-xml-api-use-cases/configure-saml-20-authentication-api.html)
This solves my issue of not being able to import a SAML metadata configuration I'm getting from Azure to …
> Added option to import a SAML metadata profile.

- plugins/modules/panos_facts.py
In the module `panos_facts.py`, the method `Interfaces` is, amongst other things, supposed to add the configured ipv6 addresses to the interfaces. For subinterfaces this doesn't work though, because instead of checking the type of the subinterface children to be `IPv6Address`, the method checks the type of the subinterface itself, therefore never adding ipv6 addresses to subinterfaces. The implemented fix is basically based on the code that adds ipv6 addresses to "normal" layer 3 interfaces which is also part of the `Interfaces` method.
While gathering information about different systems with `panos_facts.py`, I noticed the following:
Without the changes, the module never adds any ipv6 address to subinterfaces, even though the code aims to do that. With the changes, the module is now …
> panos_facts: fixed addition of ipv6 addresses to subinterfaces

- plugins/modules/panos_security_rule.py
> docs(panos_security_rule): Clarified `source_ip` and `destination_ip`

- plugins/modules/panos_nat_rule.py
After upgrading to version 2.8.0 my panos_nat_rule no longer worked. I was getting a key error, see below, 
Error: 
```JSON
"module_stderr": "ansible_collections/paloaltonetworks/panos/plugins/modules/panos_nat_rule.py\", line 339, in create_nat_rule\nKeyError: 'dnat_dynamic_address'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1} 
```  
I have corrected this by adding the below to the objects and parsing those params into the function call so create_nat_rule will no longer throw an error when those parameters are not supplied.
- dnat_dynamic_address
- dnat_dynamic_port
- dnat_dynamic_distribution
The change is required because it breaks anything not using the dnat_dynamic_address.
Haven't opened an issue - I wanted to see if I could fix …
> Bugfix panos_nat_rule.py dnat_dynamic_address

- plugins/module_utils/panos.py
Change error message and update comment in code for pandevice/pan-os-python minimum version
Current error message states "panos version < minimum" which infers PAN-OS version on firewall/Panorama is below minimum. What is really meant is that the pan-os-python package is not at the minimum version, not the PAN-OS devices.
Single string update, tested locally
> Improve minimum package error message

- docs/source/examples.rst
This fixes a typo in the docs that can cause confusion on how to use the panos_admpwd module.
This solves any confusion brought about by the panos_admpwd module example.
NA
NA
Document update
> Fix wrong variable name on panos_admpwd example

- plugins/modules/panos_software.py
allow panos_software to perform downgrades in addition to upgrades
panos_software no longer allows the user to perform a software downgrade. This patch allows a downgrade operation by verifying the version sequence. I.e. 1 minor or major step at a time.
Downgrades are a requirement that should be supported. If an upgrade fails for some reason, we should be able to use panos_software to rollback.
Use panos_software module with a desired version less than the current version
simple logic to check if desired_version is less than current version by no more than 1 
Not being able to downgrade is a bug that was introduced some time ago.
> Allow downgrade in panos_software.py

- plugins/modules/panos_bgp_policy_rule.py
Adding conditional check for address_prefix to check it is populated
Whilst PAN-OS and and pan-os-ansible both agree it is optional, the code runs a loop that assumes a value will be present, and when there has been no value specified for address_prefix in the user's playbook, the execution fails because the for loop can't run on an empty value
Problem found during lab testing. Code change tested on local machine per method described in the contributing guide.
I attempted to run `ansible-test sanity --local` per the contributing guide, but after battling various challenges of python versions, package dependencies, pyenvs, and stuff not installing during the execution of the  `ansible-test sanity --local`, I gave up, sorry.
Before and after screenshot:
- Bug fix (non-breaking change which …
> Adds conditional for address_prefix

- .github/do-release.sh
Adding extra step to publishing workflow, which will upload the collection to Automation Hub
Publishing to Automation Hub is part of becoming certified, and we are required to dual publish, both to the original Galaxy but also to Automation Hub as well.
Tested via Automation Hub (unable to test CLI at the moment due to API key)
N/A
> Add AutomationHub publishing alongside Galaxy

- plugins/modules/panos_export.py
Fix for exporting tech-support and stats-dump files.
Looking to fix #359.
This issue appears to have been present since the 2.6.0 release.
Per #359, exporting tech-support and stats-dump files were failing because since 2.6.0, export_binary function needs a category value.
- The existing call of export_binary from within export_async: `export_binary(module, xapi, filename)`
- The error produced:
```
TASK [Download Stats Dump File] ***********************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: export_binary() missing 1 required positional argument: 'filename'
fatal: [firewall]: FAILED! => {"changed": false, …
```
> fix(panos_export): Fix: export_async

- .github/do-release.sh
- .github/workflows/ci.yml
Updated publishing method for dual publishing to both Galaxy and AutomationHub
Previously AutomationHub publishing was untested, now it is tested
Locally on laptop
- CI
> ci: Updated CI for push to Galaxy and AutomationHub

- plugins/modules/panos_commit_push.py
Adding support for the [PAN-OS 10.2 feature](https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-release-notes/features-introduced-in-pan-os/panorama-features) of Administrator-Level Push from Panorama to Managed Devices
Depends upon [supporting change in pan-os-python](https://github.com/PaloAltoNetworks/pan-os-python/pull/485).
Motivation is adding support for a new PAN-OS feature, and also to support adding this feature in pan-os-ansible ([ref - will close this issue](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/361))
Tested locally, with Panorama 11.0.0 and managed firewall 10.2.3
```
tasks:
- name: Commit and Push template configuration
panos_commit_push:
provider: "{{ device }}"
style: "device group"
name: "poc-dg"
admins:
- "other"
include_template: no …
```
> Add per-admin parameter to Panorama push

- .github/workflows/automationhub_token_keepalive.yml
GitHub Action to do keepalive for the AutomationHub Token
Inactive tokens expire after 30 days, this will stop the 30 day timer with regular check-ins
Command tested successfully locally on laptop CLI
- CI
> ci: Keepalive for AutomationHub Token

- plugins/modules/panos_lic.py
One line of extra docs to clarify a use case
Clarification of the use case came to light after a user question. When using panos_lic, force: true should be used when adding licenses for features/subscriptions to a firewall which already has a serial number (e.g. PA-Series, or licensed VM-Series, etc)
No testing, docs update only
N/A
- One line documentation update
> Adds clarification on use case for force-true on panos_lic

- plugins/modules/panos_software.py
One line added to refresh the device's version before attempting to access it in `panos_software.py`.
Was getting the following error when trying to use the `panos_software` module,
```
/var/folders/sb/wzby_gw52ybcdk_xzvfnmg2w0000gp/T/ansible_paloaltonetworks.panos.panos_software_payload_ia1b1v9h/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py:172: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
/var/folders/sb/wzby_gw52ybcdk_xzvfnmg2w0000gp/T/ansible_paloaltonetworks.panos.panos_software_payload_ia1b1v9h/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py:179: …
```
> Refresh device version before accessing attribute

- plugins/modules/panos_security_rule_facts.py
Fix a typo in the params for ```panos_security_rule_facts```
Per https://github.com/PaloAltoNetworks/pan-os-ansible/commit/c671a4160a3911f6c5eca46c2644616e64ae1332#commitcomment-97529680
N/A
> fix(panos_security_rule_facts): params typo

- plugins/modules/panos_ipsec_ipv4_proxyid.py
Fix IPv4 ProxyID `number_proto` parameter, and also clarify usage in documentation
Fixes #385
Locally
> fix(panos_ipsec_ipv4_proxyid): Fix IPv4 ProxyID proto parameter

- plugins/modules/panos_export.py
The function `export_binary` was changed to include an extra parameter (`category`), but in several places, the function was being called without passing the `category` parameter. Similar to [PR360](https://github.com/PaloAltoNetworks/pan-os-ansible/pull/360), adding the parameter into calls of export_binary duplicated the calls of xapi.export. In PR360 I duplicated the code from `export_binary` into the calling function; this was not very DRY, but worse, this code would now need to be duplicated several times to fix other code (such as [exporting certs](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/297), PCAPs etc). Instead, I created a `save_binary` function, to make this code DRY; it is the same function code as `export_binary` except it removes the duplicate call to …
> fix(panos_export): Fix binary exports

- plugins/modules/panos_commit_push.py
Adds messaging for the use when a panos_commit_push operation fails
Fixes #403
It looks like the `messages` that were previously being returned in `module.fail_json` are always empty for a commit_push. The messages content is now a few levels deeper, and is returned per device, needing some iteration of the devices being targeted with the `commit_push` in order to surface them to the user.
Tested locally.
With a single managed device:
```
TASK [Commit and push config via Panorama] *****************************************************************************************
fatal: [host_homelabrama]: FAILED! => {"changed": false, "msg": "Job ID 1235286: vm-series-test: Validation Error: |  address -> aaaa-123123 'aaaa-123123' is already in use |  address is invalid | vsys1 |     Error: …
```
> fix(panos_commit_push):commit_push fail messaging

- .github/workflows/ci.yml
- .releaserc.json
- docs/contributing.md
Adds plugin to semantic-release to generate changelog files
Replaces the current system, where `CHANGELOG.md` points to the GitHub releases page
Tested on a separate repo. Needed to alter changelog plugin version from 6.0.0 to 5.0.1 in order to satisfy dependencies with existing versions of other plugins. Initial fail:
```
$ npm install conventional-changelog-conventionalcommits@^4.4.0 @semantic-release/changelog@^6.0.0 @semantic-release/git@^9.0.0 @semantic-release/exec@^5.0.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: semantic-release@20.1.0
npm ERR! node_modules/semantic-release
npm ERR!   peer semantic-release@">=18.0.0" from @semantic-release/changelog@6.0.2
npm ERR!   node_modules/@semantic-release/changelog
npm ERR! …
```
> ci: Add changelog generator to CI

- plugins/modules/panos_security_rule.py
Docs update, clarifying PAN-OS versions for the HIP profile parameter
It came up during a [customer query on LIVEcommunity](https://live.paloaltonetworks.com/t5/automation-api-discussions/error-certfile-should-be-a-valid-filesystem-path/td-p/539882)
N/A - Docs
- Breaking change (fix or feature that would cause existing functionality to change)
N/A - Docs
> docs: HIP profile PAN-OS version clarification

- plugins/modules/panos_http_profile.py
- plugins/modules/panos_http_profile_header.py
- plugins/modules/panos_http_profile_param.py
Adds the option for HTTP Server Profiles to key off Decrypt and GP logs.
Whilst I was there, I also alphabetically ordered the `choices` in the docs for the header/params modules.
Decrypt and GP logs were added in PAN-OS 10.0 and 9.1 respectively.
This feature coverage is also useful for upcoming Event-Driven Ansible operations.
Tested locally ([playbook](https://github.com/jamesholland-uk/playground/blob/main/pan-os-ansible/http-server-profiles.yml))
> feat(panos_http_profile): feat: Decrypt and GP for HTTP profiles

- plugins/modules/panos_log_forwarding_profile_match_list.py
Add decryption log-type to log forwarding
Decryption logs were added in PAN-OS 10.0
Tested locally with Ansible
Before:
After:
> feat(panos_log_forwarding_profile_match_list): Add decryption log-type to log forwarding

- plugins/modules/panos_software.py
Adding an option to load a name config during the process.
An option to load a named config after and upgrade/downgrade is introduced. This can be helpful especially during downgrades. 
This module, in this form, was already used on production. 
> feat(panos_software): name config load option

- plugins/modules/panos_import.py
Adds the ability, at the time of importing a keypair, to block the private key from being exported from PAN-OS in future
Closes #415
[Blocking export of private keys was introduced in PAN-OS 10.0](https://docs.paloaltonetworks.com/pan-os/10-0/pan-os-new-features/decryption-features/block-export-of-private-keys)
Tested locally
Testing screenshot:
> feat(panos_import): Add private key blocking to keypair import

- tests/config.yml
This PR adds a config file which controls the version of Python used for unit and sanity tests. The version in the config file matches the currently version currently supported by the collection, `>=3.8`.
Currently, during collection import to Galaxy/AutomationHub, compile errors are observed during sanity tests for Python versions 2.7 and 3.5:
```
Running sanity test "compile" on Python 2.7 
ERROR: Found 3 compile issue(s) on python 2.7 which need to be resolved: 
ERROR: plugins/module_utils/panos.py:707:35: SyntaxError: **ref_spec, 
ERROR: plugins/modules/panos_config_element.py:293:32: SyntaxError: f"<{outer}>" + element_xml + f"</{outer}>" 
ERROR: plugins/modules/panos_userid.py:119:21: SyntaxError: **extras, 
See documentation for help: …
```
> test: add python version for tests

- .github/workflows/ci.yml
Adds version specification within CI for `antsibull-docs`
`antsibull-docs` released v2.0 which was used by the docs task in CI for the most recent release, and this had a dependency issue with Python versions. Reverting to using v1.11.0 fixes the issue
Tested locally
Before this fix (`antsibull-docs` v2.0):
After this fix (`antsibull-docs` v1.11.0):
> ci: Fix for antsibull-docs v2 dependency issue

- plugins/modules/panos_ike_crypto_profile.py
IKE profile takes `non-auth` and not `none` as an authentication hash type.
```
TASK [palo_alto : Create Secure IKE Crypto Profile] ***************************************************************************************
fatal: [TEST_PaloAlto.hostname]: FAILED! => {"changed": false, "msg": "Failed apply:  TEST-IKE-Crypto-Profile -> hash 'none' is not an allowed keyword\n TEST-IKE-Crypto-Profile -> hash is invalid"}
```
`aes-gcm-256` encryption has built in authentication, so you need to set the authentication to `non-auth`.
Tested running the following on Rocky 8:
```
- name: Create Secure IKE Crypto Profile
paloaltonetworks.panos.panos_ike_crypto_profile:
ip_address: "{{ firewall_ip }}" #TEMP FOR SCRIPT TESTING, Used for ansible connection to PA
username: "{{ username }}"
password: "{{ …
```
> Fixed auth type `non-auth` for IKE profile

- plugins/modules/panos_bgp_peer_group.py
Fix for IBGP `export_nexthop` choices, adding `original` which is a valid choice for IBGP.
**Note:** The default for `export_nexthop` is currently `resolve` which is not valid for IBGP. Users choosing `type: ibgp` will therefore need to explicitly choose `original` or `use-self` for `export_nexthop`, leaving `export_nexthop` undefined will cause an error. Changing the default for `export_nexthop` would constitute a breaking change, so this is why the PR's code is presented as just an extra choice, not a change to the default choice.
Fixes #441
Tested locally:
```
- name: Create BGP Peer Group
paloaltonetworks.panos.panos_bgp_peer_group:
provider: "{{ device }}"
name: "network4"
type: "ibgp"
enable: true
export_nexthop: 'original'
```
Test success:
- Bug fix (non-breaking change which …
> fix(panos_bgp_peer_group): Fix for IBGP export next-hop options

- plugins/modules/panos_import.py
Notes clarifying choices for importing certs and keys, `certificate` versus `keypair`.
More than once, users have been using these two choices incorrectly. Updating docs to aid user education.
N/A
- Docs
> docs(panos_import): Notes for importing certs and keys

- plugins/modules/panos_admpwd.py
Fix success criteria.
Update example in docs.
Fixes #433.
Per #433, previously the test for success was too generic and was detecting a failed result as success.
Whilst testing for this PR, the example in the documentation was noted to be incorrect since changes in Ansible functionality, so the example code has also been updated.
Tested locally against VM-Series and Panorama.
Example of a previous failure, that the module detected as success:
Example of success after the changes in this PR:
> fix(panos_admpwd): Fix success criteria and update example in docs

- plugins/modules/panos_software.py
Modifies the valid sequence to only be checked if the user is attempting an installation, leaving it unchecked for downloads.
Fixes #454.
It is permitted by PAN-OS to download software which would not be valid to install at the present time, thus allowing the user to pre-download software ready for a later installation, which speeds up the installation work in a change window. Currently the valid sequence check, used to ensure a valid install path is used, is enforced for downloads too. This change removes the check for downloads, as is allowed by PAN-OS.
The alternative approach is a large change to the code. There would be separate checks for valid download paths and valid installation paths. There is different logic for the validity of each upgrade/downgrade path. There are also …
> fix(panos_software): Modify valid sequence for downloads only

- docs/source/authors.rst
- docs/source/examples.rst
Documentation updates for EDA for launch
Documentation updates for EDA for launch
N/A
N/A
- Docs
> docs(event-driven ansible): Add inventory and playbook

- extensions/eda/plugins/event_source/logs.py
Updated code for Red Hat's certification checks. Fixes failure of checks executed by `ruff` with `tox` for EDA code.
UPDATE: Fixes clashed with `ansible-sanity` checks, so were backed out per review with Ansible Partner Engineering, and instead a skip was put in for the ruff test `FA102`.
The `tox` testing/linting tool required by Red Hat as part of EDA certification is not version pinned/ranged. The `ruff` tool (executed with `tox`) moved from 0.0.283 to 0.0.284, then we started to get new errors, with no changes to the code:
```
extensions/eda/plugins/event_source/logs.py:104:14: FA102 Missing `from __future__ import annotations`, but uses PEP 585 collection
extensions/eda/plugins/event_source/logs.py:106:6: FA102 Missing `from __future__ import annotations`, but uses PEP 585 collection …
```
> fix(event-driven ansible): Updated code for Red Hat's certification checks

- meta/extensions.yml
Adding the `meta/extensions.yml` file, which is required to display EDA content in documentation on Automation Hub. This file points to the EDA plugin paths inside the collection. 
Eventually, `ansible-doc` will use this file to display EDA plugins and list their full contents on Automation Hub, exactly like other Ansible plugins. This feature is in development. Currently, galaxy-importer directly consumes this file to display EDA plugins in Automation Hub. Without this file, EDA plugins are not listed in the collection's "content" list.
This is the confirmed way to display EDA plugins on Automation Hub. All future EDA collections will be asked to include this file. 
> Adding meta/extensions.yml file to display EDA on Automation Hub

- plugins/modules/panos_device_group.py
Change logic in the Device Group module so the DG hierarchy is only refreshed/updated if the user inputs `state` as `present`, `merged` or `replaced`, and therefore by implication, not refreshed/updated when the user inputs `state` as `gathered`, per #464 
Fixes #464 
Tested locally
Before and after testing:
> fix(panos_device_group): Do not move a Device Group if state is set to gathered

- README.md
- SUPPORT.md
- docs/source/index.rst
- Updating support statements in various places, to reflect official support for Ansible subscribers, community support for others.
- Updating links to live.paloaltonetworks.com to be pan.dev instead
- Some support statements gave a visual interpretation that only community support was available
- The developer presence is moving from live.paloaltonetworks.com to focus on pan.dev
N/A
> docs: More updates for support statements and documentation

- .github/workflows/ci.yml
- plugins/modules/panos_admin.py
- plugins/modules/panos_administrator.py
- plugins/modules/panos_application_group.py
- plugins/modules/panos_bgp_policy_filter.py
- plugins/modules/panos_bgp_policy_rule.py
- plugins/modules/panos_commit.py
- plugins/modules/panos_commit_firewall.py
- plugins/modules/panos_commit_panorama.py
- plugins/modules/panos_commit_push.py
- plugins/modules/panos_custom_url_category.py
- plugins/modules/panos_dhcp_relay.py
- plugins/modules/panos_ha.py
- plugins/modules/panos_ike_gateway.py
- plugins/modules/panos_l3_subinterface.py
- plugins/modules/panos_loadcfg.py
- plugins/modules/panos_op.py
- plugins/modules/panos_region.py
- plugins/modules/panos_sag.py
- plugins/modules/panos_security_rule_facts.py
- plugins/modules/panos_template.py
- plugins/modules/panos_template_stack.py
1. Updating per-module code examples to comply with new requirements of `ansible-lint`
2. Updating CI to fix ansible-lint execution
Note: Wouldn't normally put two changes in one PR, but both are required to pass `ansible-lint` due to changes listed below.
1.`ansible-lint` is now checking the examples code where it previously did not [(ref)](https://github.com/ansible/ansible-lint/pull/3309), and `ansible-lint` is a requirement for certification.
2. `ansible-lint` had a breaking change within a minor release [(ref)](https://github.com/ansible/ansible-lint/issues/3801) which required a CI change to fix on our side
Tested locally with ansible-lint 6.20.4.dev4 and on a personal fork of this repo
> CI & docs: Update CI and update examples for ansible-lint

- Makefile
- plugins/module_utils/panos.py
- plugins/modules/panos_export.py
- plugins/modules/panos_facts.py
- plugins/modules/panos_import.py
- plugins/modules/panos_object.py
- plugins/modules/panos_query_rules.py
- plugins/modules/panos_redistribution.py
- tests/unit/httpapi/test_panos.py
- tests/unit/plugins/module_utils/test_panos.py
Remove unused imports to pass pylint testing.
Remove `skip` for pylint testing in CI.
Fixes #490
Tested locally with integration tests in this repo
Before changes:
After changes:
> fix(various): Remove unused imports for pylint testing

- .releaserc.json
- README.md
- docs/source/index.rst
Update links pointing to Ansible Galaxy
The URL format has changed. [URL update notification](https://github.com/ansible-collections/news-for-maintainers/issues/59)
Tested locally
> docs: Updates for new Galaxy URL format

- .github/workflows/ci.yml
- meta/runtime.yml
In CI workflow action for Ansible linter is used, which was recently updated (https://github.com/ansible/ansible-lint/commit/cba7c512bb94a2ad36109f20358475ae18c88bc6) and requires now Ansible in version `2.14.0, <2.16`.
In PR beside change of required Ansible version, there were removed sanity tests on Ansible 2.13 and using `ansible-core^2.14` in CI workflow steps.
CI workflow stopped to work.
Moreover Ansible 2.13 is EOL (https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix).
Code was tested by running workflow.
> chore: Update required Ansible version

- README.md
- pyproject.toml
According to https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix, minimum version of Python for `ansible-core 2.14` is `Python 3.9`.
Release action failed on step for documentation: https://github.com/PaloAltoNetworks/pan-os-ansible/actions/runs/7194066471/job/19593939780#step:5:108
Code was checked locally by command: `poetry add ansible-core^2.14`
> fix: define in pyproject.toml Python 3.9 for ansible-core 2.14

- extensions/eda/plugins/event_source/logs.py
Tox ruff checks in CI for EDA partner testing was failing due to required linting. This PR fixes the below error for this check to pass.
ruff checks was failing because of a blank line required after "Returns" section in docstrings.
```
ruff: commands[0]> ruff check --select ALL --ignore INP001 -q ../../extensions/eda/plugins
/home/runner/work/pan-os-ansible/pan-os-ansible/extensions/eda/plugins/event_source/logs.py:57:5: D413 [*] Missing blank line after last section ("Returns")
/home/runner/work/pan-os-ansible/pan-os-ansible/extensions/eda/plugins/event_source/logs.py:68:5: D413 [*] Missing blank line after last section ("Returns")
ruff: exit 1 (0.01 seconds) /home/runner/work/pan-os-ansible/pan-os-ansible/.github/workflows> ruff check --select ALL --ignore INP001 -q …
```
> docs: fix eda ruff docs linting

- SUPPORT.md
Updating support.md file with new legal verbiage.
@alperenkose for docs updates like this, is it safe to simply commit them to the main branch here with a proper commit message? I didn't want to trigger a release accidentally.
> chore: Update SUPPORT.md

- plugins/modules/panos_custom_url_category.py
Fix for `name` parameter description in `panos_custom_url_category` module.
bugfix
n/a
> docs: fix custom url category "name" parameter description

- plugins/modules/panos_facts.py
This PR fixes #532 .
Wrong fact name.
Local library and test file:
```yaml
TASK [Print vsys facts] ****************************************************************************
ok: [panorama-mgmt-main] => {
"vsys": {
"ansible_facts": {
"ansible_net_full_commit_required": false,
"ansible_net_gather_subset": [
"system",
"vsys"
],
"ansible_net_hostname": "vma-test",
"ansible_net_model": "PA-VM",
"ansible_net_multivsys": "off",
"ansible_net_serial": "",
"ansible_net_uncommitted_changes": false,
"ansible_net_uptime": "0 days, 4:38:10",
"ansible_net_version": "11.1.0",
"ansible_net_virtual_systems": [
{
"vsys_currentsessions": "3",
"vsys_description": null,
"vsys_id": "1",
"vsys_iflist": [
"ethernet1/1",
"ethernet1/2"
],
"vsys_maxsessions": "0",
"vsys_name": "vsys1",
"vsys_vrlist": [], …
```
> fix(panos_facts.py): Fixed virtual systems fact name

- extensions/eda/plugins/event_source/logs.py
- plugins/modules/panos_l2_subinterface.py
- plugins/modules/panos_l3_subinterface.py
- tests/integration/firewall/test_panos_l2_subinterface.yml
- tests/integration/firewall/test_panos_l3_subinterface.yml
Add new `parent_interface` parameter for `panos_l2_subinterface` and `panos_l3_subinterface` modules. The parameter is optional, except for case when state is set to `gathered`.
So far the parent interface has only been derived from subinterface name. This does not work with gathered state - for example when filter is based on the subinterface name - if it's not provided as a param, modules will fail (see linked issue).
Resolves #498 
Tested locally as well as using newly added integration tests.
> fix: Add 'parent_interface' parameter for l2/l3 subinterface modules

- plugins/modules/panos_active_in_ha.py
In customer projects we tended to use local version of `panos_active_in_ha` library and we couldn't switch to the remote module in the collection because in the playbooks we were using `ignore_non_functional` option. This PR adds it.
#559 
Tested the module as a local copy in a playbook.
> feat: Add new option to panos_active_in_ha module

- plugins/modules/panos_active_in_ha.py
- plugins/modules/panos_readiness_checks.py
- plugins/modules/panos_snapshot_report.py
- plugins/modules/panos_state_snapshot.py
Some links in the documentation had a typo for panos-upgrade-assurance
Prevent somone installing a wrong package
only docs changed
docs
> docs: replaced pan-os-upgrade-assurance with panos-upgrade-assurance

- plugins/modules/panos_readiness_checks.py
- plugins/modules/panos_snapshot_report.py
In customer projects we were using local copies of the following modules:
* `panos_readiness_checks.py`
* `panos_snapshot_report.py`
They had some additional Try Except blocks that were not present in public modules. This PR aims to introduce them.
#559 
These changes were introduced in local libraries used earlier in Upgrade Automation playbooks.
> feat: Add additional error handling to some upgrade assurance modules

- docs/source/index.rst
Fixed the version in the [Installation Guide](https://paloaltonetworks.github.io/pan-os-ansible/index.html#installation) due to Ansible version information below.
- >Ansible versions before 2.14 are not supported.
- in README,md
- > requires_ansible: '>=2.14.0'
- in meta/runtime.yml
Due to confusion between different versions of  Installation Guide and meta/runtime.yml
Document only.
> fix required ansible-core version

- Makefile
- requirements.txt
`requirements.txt` file with hashes causing issues for generating Ansible Execution Environment image when combined with other collections. PR removes hashes from the `requirements.txt` file. 
`make reqs` command in Makefile is also updated to exclude hashes (this command is not being used in the CI yet)  
Tested installing locally on a virtualenv.
> fix: requirements.txt update python version and remove hashes

- docs/source/gatheredfilter.rst
- plugins/module_utils/panos.py
Regex expressions in `gathered` state `gathered_filter` required extra escape chars which wasn't a valid regex in deed. 
This PR allows to write valid regex expression in the `gathered_filter`, the previous syntax is not valid anymore hence this is introducing a breaking change.
`shlex.split()` was used to split logic expressions in the `gathered_filter`, which also escaped(removed) backslash `\` chars from the expression and led to a non-working regex. We have implemented our split method using shlex but removing backslash(`\`) escape char from shlex instance to avoid escaping and properly processing regex expressions.
Fixes #579 
Tested on vm firewalls with examples in the issue.
- Breaking change (fix or feature that would cause existing functionality to change)
> fix!: gathered_filter to process regex correctly

- plugins/module_utils/panos.py
- plugins/modules/panos_static_route.py
- plugins/modules/panos_template.py
This is an alternative approach for mitigating issues on passing `None` value to sdk for params which have default values in order to remove an xpath.
#587 PR and relevant pan-os-python changes would not be needed if we prefer this approach.
We are using default values for `None` provided params for newly created/replaced objects which can cause issue when SDK requires an actual `None` type input to remove an xpath. 
For example pan-os-python does not accept `'none'` string value for the nexthop type in StaticRoute but it requires nexthop type to be `None` type in order to be removed (in order words set to `"None"` in GUI), although it has a default value of `'ip-address'`. Normally we expect to use default values from SDK when the param is `None` type but this kind of cases breaks this …
> fix: object_handling method for overriding defaults

- extensions/eda/plugins/event_source/logs.py
- plugins/modules/panos_state_snapshot.py
- pyproject.toml
- requirements.txt
panos-upgrade-assurance 1.4.0 allows to provide snapshot configs as dict element in addition to str. Just like readiness checks. This change allows dict element to be provided for snapshot config elements passed to `panos_state_snapshot` module. upgrade assurance requirement is also bumped as a result of this.
Tested locally with playbook implementation.
> feat(panos_state_snapshot): allow dict config element for snapshots

- plugins/modules/panos_software.py
Skipping 3 major/minor releases is allowed for both upgrade and downgrade paths for PAN-OS devices supporting Skip Software Version Upgrade feature starting from 10.1 onwards.
Downgrade path is limited to min. 10.1.x release when downgrading from Skip Software Version Upgrade supported PAN-OS devices.
Fixes #553 #629 
also supercedes #599 allowing to skip 3 major/minor releases after 10.1.x
Tested with local playbook.
> feat(panos_software): support Skip Software Version Upgrade
