PaloAltoNetworks/pan-os-ansible

plugins/modules/panos_object_facts.py
This call could return `None` in certain instances, so check for it.
- Breaking change (fix or feature that would cause existing functionality to change)
=> panos_object_facts: Check for none on getattr call.

plugins/module_utils/panos.py
@stealthllama @mrichardson03 
This PR adds a new flag, `template_is_optional` to the helper class.  Objects such as administrators or log forwarding profiles that can exist both in a template and locally on Panorama can now be locally configured on Panorama by specifying this flag as `True` when creating the helper object.
=> needed for #43

plugins/module_utils/panos.py
Fixing wrong **else if** to elif
I'm testing the develop branch and it is broken at the moment.
Tested locally and it works
=> Fix wrong else if

plugins/modules/panos_application_object.py
Add module for application objects.  Related to #75.
Tested against PAN-OS 10.0.0.
=> feat: add panos_application_object

plugins/module_utils/panos.py
Update the helper connection lib to support both pan-os-python and pandevice
=> feat: helper support for pan-os-python

plugins/modules/panos_custom_url_category.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt
=> refactor: Remove custom CustomUrlCategory class

plugins/modules/panos_commit.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt
=> docs: Mark panos_commit deprecated in 3.0.0

plugins/modules/panos_registered_ip.py
=> fix: Adding tags to ip address would fail

plugins/modules/panos_bgp_policy_filter.py
See https://github.com/PaloAltoNetworks/pan-os-ansible/issues/116 for commentary.
Fixes #118
=> fix: address_prefix should be list of type dict

plugins/modules/panos_security_rule.py
=> fix: panos_security_rule should support "shared"

meta/runtime.yml
=> fix: Require Ansible 2.9.10 or greater (#133)

plugins/modules/panos_facts.py
Panorama HA returns a slightly different XML response than firewall HA.
Fixes #139
=> fix(panos_facts): Fix Panorama HA data collection

plugins/modules/panos_ike_gateway.py
=> feat(panos_ike_gateway): Add fqdn to peer_address_type

plugins/modules/panos_application_filter.py, plugins/modules/panos_application_group.py, plugins/modules/panos_dynamic_user_group.py, plugins/modules/panos_region.py, plugins/modules/panos_schedule_object.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt
Add panos_application_filter, panos_application_group, panos_dynamic_user_group, panos_region, panos_schedule_object
Fixes #75
=> feat: Add additional object modules

plugins/modules/panos_import.py
Fixes #68
Support many more categories in `panos_import`:
- anti-virus
- application-block-page
- captive-portal-text
- certificate
- configuration
- content
- credential-block-page
- credential-coach-text
- custom-logo
- data-filter-block-page
- device-state
- file-block-continue-page
- file-block-page
- global-protect-client
- global-protect-clientless-vpn
- global-protect-portal-custom-help-page
- global-protect-portal-custom-home-page
- global-protect-portal-custom-login-page
- global-protect-portal-custom-welcome-page
- high-availability-key
- keypair
- license
- logdb
- mfa-login-page
- pandb-url-database
- plugin
- safe-search-block-page
- saml-auth-internal-error-page
- signed-url-database
- software
- ssl-cert-status-page
- ssl-optout-text
- url-block-page
- url-coach-text
- …
=> feat(panos_import): Add additional import options

plugins/modules/panos_aggregate_interface.py
=> feat(panos_aggregate_interface): Support LACP

plugins/modules/panos_custom_url_category.py
=> fix(panos_custom_url_category): Fix imports for pandevice

plugins/modules/panos_object_facts.py
Added applications and application groups to panos_object_facts module
=> Add applications and application groups to panos_object_facts

plugins/modules/panos_op.py
Added support for vsys in panos_op the module
=> feat(panos_op): Added support for vsys

plugins/modules/panos_custom_url_category.py
Added support for description field on custom URL category and fixed an typo in the Example.
=> Added support for description field and fixed typo in the example

.github/workflows/ci.yml, docs/source/examples.rst, plugins/modules/panos_commit_firewall.py, plugins/modules/panos_commit_panorama.py, plugins/modules/panos_commit_push.py, plugins/modules/panos_l3_subinterface.py, plugins/modules/panos_security_rule_facts.py, plugins/modules/panos_zone.py
=> test: Fix ansible-test sanity errors

plugins/modules/panos_match_rule.py
=> fix(panos_match_rule): Fix exception on match failure

plugins/modules/panos_match_rule.py
=> fix(panos_match_rule): Always return rule result

plugins/modules/panos_nat_rule.py
=> feat(panos_nat_rule): Support target, negate_target

plugins/modules/panos_export.py
=> fix(panos_export): Fix export_binary

plugins/httpapi/panos.py, plugins/module_utils/panos.py, plugins/modules/panos_config_element.py, tests/integration/firewall/test_panos_config_element.yml, tests/integration/inventory.example, tests/unit/httpapi/test_panos.py, tests/unit/plugins/modules/common/utils.py, tests/unit/plugins/modules/test_panos_config_element.py
* Change panos_config_element to only support httpapi connection.
* Fixed idempotence for set action with single element, added to unit test.
=> feat: Add httpapi connection

Makefile, plugins/modules/panos_device_group.py, requirements.txt, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
=> feat: Add device group support

plugins/modules/panos_nat_rule.py
=> feat: Add NAT rule dynamic dest xlate support

plugins/module_utils/panos.py, plugins/modules/panos_device_group.py
=> fix: Do targetted updates in panos_device_group

plugins/modules/panos_template_variable.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
=> feat: Add `panos_template_variable`

.github/workflows/ci.yml
This will allow docs fixes without mandating a release.
=> chore: build collection from local

plugins/modules/panos_object_facts.py
Added support for Custom URL Categories in panos_object_facts.py
Needed to be able to read from objects.CustomUrlCategory.
Test task:
`
---
- name: Get running config url categories
paloaltonetworks.panos.panos_object_facts:
provider: '{{ provider }}'
object_type: 'custom-url-category'
field: 'name'
field_search_type: 'regex'
field_search_value: '.*'
register: running_custom_url_categories
- name: Print all url categories
debug:
var: item
with_items:
- '{{ running_custom_url_categories }}'
`
Test output:
`
$ ansible-playbook panos.yaml -l <HOST> --tags url_test --ask-vault-pass
Vault password:
PLAY [panos playbook] **************************************************************************************
*
TASK [panos : load secret vars] …
=> feature(panos_object_facts): Added support for Custom URL Categories

plugins/modules/panos_ike_crypto_profile.py
=> feat(panos_ike_crypto_profile): Add additional parameter values

README.md, docs/source/index.rst
Adding statements/wording to update users on the official support status for Red Hat Ansible subscribers.
Documentation update to reflect new certified and supported status.
Documentation updates viewed locally.
- Documentation only
=> Adds statement about official support

.github/publishing.md
Adding docs for the publishing process for AutomationHub (and Galaxy)
Docs for future reference
N/A, maintainer reference docs only
- Maintainer docs
=> docs: Publishing process for AutomationHub

pyproject.toml, requirements.txt
Updating pan-os-python version to 1.8.0
=> ci: Update pan-os-python to 180

.github/workflows/ci.yml
=> ci: Update Python to 3.9

plugins/modules/panos_decryption_rule.py, plugins/modules/panos_nat_rule2.py, plugins/modules/panos_pbf_rule.py, plugins/modules/panos_security_rule.py
Docs update to cover the scenario referenced in #377
Docs update to cover the scenario referenced in #377
N/A - docs
- Docs
=> docs: Use of predefined EDLs in security rules

plugins/modules/panos_nat_rule.py
Fix for params in helper
Fixes #380
Tested locally, patching local collection
Testing, before and after
=> fix(panos_nat_rule): fix panos_nat_rule helper params

plugins/modules/panos_commit_push.py
Re-attempt of [previous PR](https://github.com/PaloAltoNetworks/pan-os-ansible/pull/405), which did not trigger a release
=> fix(panos_commit_push): commit_push fail messaging

README.md
Fixed wrong option of debug module example in readme.
I want to be able to make the first steps of using collections correctly.
(Documentation fix only)
=> Fixed Playbook example in readme

tests/integration/README.md, tests/integration/firewall/test_panos_decryption_rule.yml, tests/integration/inventory.example
Adds integration tests for decryption policies
To give integration testing more coverage
Tested locally
- Extra tests
=> test: Add integration test for decryption policies

plugins/modules/panos_export.py
Create the directory when exporting if it didn't already exist.
Updated version on https://github.com/PaloAltoNetworks/pan-os-ansible/pull/388
Don't know quite how to reuse that same pull request
As requested by @jamesholland-uk, creating directories is `False` by default and the user is able to set it to true
When exporting to a path, it can occur that the directory doesn't exist.
This will give an error, setting `create_directory` to `True` the directory gets created and the file succesfully exported.
Run `panos_export` with the `filename` variable to a location where the directory doesn't exist.
After running with the changes the directory get created and the exported file appears.
=> feat: Create directory if it doesn't exist

extensions/eda/plugins/event_source/logs.py
Make `custom_logger` argument optional
Fixes #455
Tested locally
=> fix(eda): Make `custom_logger` argument optional

docs/source/examples.rst
Typos and corrections for EDA docs
Found during review
N/A - Docs update only
N/A
=> docs: EDA typo and updates

plugins/module_utils/panos.py
Update the logic within `gathered_filter` for cases where a gathered parameter evaluates to `None`
Fixes #474
Tested locally
=> fix(gathered_filter): Update logic to cover cases of None

plugins/module_utils/panos.py
Fix error handling for no-value operators
Looking to fix issue #473
Tested locally
Testing, before and after:
=> fix(gathered_filter): Fix error handling for no-value operators

.github/workflows/ci.yml
Make code format required for release
Make CI more structured
N/A
N/A
=> ci: Make code format required for release

plugins/modules/panos_active_in_ha.py, plugins/modules/panos_readiness_checks.py, plugins/modules/panos_snapshot_report.py, plugins/modules/panos_state_snapshot.py
Adding error message for panos-upgrade-assurance based modules.
Error out modules when working against a Panorama device.
Tested on local copy of the collection.
=> fix(panos-upgrade-assurance): error out panorama connections

plugins/modules/panos_active_in_ha.py, plugins/modules/panos_custom_url_category.py, plugins/modules/panos_facts.py, plugins/modules/panos_l2_subinterface.py, plugins/modules/panos_l3_subinterface.py, plugins/modules/panos_readiness_checks.py, plugins/modules/panos_snapshot_report.py, plugins/modules/panos_state_snapshot.py, tests/integration/firewall/test_panos_l2_subinterface.yml, tests/integration/firewall/test_panos_l3_subinterface.yml
5 commits from `develop` branch to be merged into `main` in order to trigger a new release.
=> chore: Trigger a new release

.github/actions/discover_python_version/action.yml, .github/update-requirements.py, .github/workflows/_discover_python_ver.yml, .github/workflows/check_requirements.yml, .github/workflows/ci.yml, .github/workflows/ee.yml, Makefile, pyproject.toml, requirements.txt, tests/config.yml
This PR introduces checks if the requirements.txt file needs an update for the pyproject.yml dependencies.
This is checked by comparing an auto generated requirements.txt file with the existing one. If any changes are needed for requirements.txt then CI will fail.
Auto generated requirements.txt file is created by poetry export and then filtering requirements to include main deps only (without hashes). And lastly the version constraints are updated in alignment with pyproject.yml file.
Note: Version constraints in pyproject.yml are updated to be compatible with PEP 508 and pip requirements. And it should be maintained in accordance with this.
requirements.txt file was manually maintained and it had strict version constraints. This led to being forgotten to update.
Also strict version …
=> ci: check if requirements file need update

.github/workflows/_discover_python_ver.yml, .github/workflows/check_requirements.yml, .github/workflows/ci.yml, .github/workflows/ee.yml
GitHub recommends pinning actions to a full length commit SHA, as this is currently the only method of using an action as an immutable release.
For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
N/A
=> Pin GitHub Actions

.github/workflows/ci.yml, .github/workflows/docs.yml, .gitignore, Makefile, plugins/modules/panos_security_rule.py
checkout to ansible_collections path and movings docs file paths removed from CI for docs workflow.
CI
=> ci: remove unneeded path tricks in docs workflow
